### ISSUE TITLE
[Bug] [GBS] GBS Support doesn't seem to work with the GUI

### ISSUE THREAD

**Issue by N-SPC700** [nununoisy/gb-presenter-rs#1]
Found a couple bugs when it comes to trying to play GBS files over the GUI:

1. GBS files with Japanese characters in its metadata (see attached for examples) break the program when loaded. A bit of an issue here because those GBSes are also likely from GBGBS which can automatically rip GBS files from GB rom images, which always appends Japanese metadata to the file. In a program like foobar2000 (very good GBS player) or nezplug++ (bad outdated program), which parse it correctly, it would look like this:
![image](https://github.com/nununoisy/gb-presenter-rs/assets/38848267/f1ed89cf-1cc3-4114-ba85-9a8b32911abc)
Example GBS: [JPMetadata.zip](https://github.com/nununoisy/gb-presenter-rs/files/11779792/JPMetadata.zip)

2. If the above GBS _does_ load, I can't select any song. I also have to manually specify the file opener to select GBS files, and once it accepts those, the song selector is broken. Even worse, I can't even render a file since it says it's not a valid file.
![image](https://github.com/nununoisy/gb-presenter-rs/assets/38848267/886a1fc9-cb5a-47c4-8f76-981cde800299)
(And yes, that is a custom windows theme. I'm just using Windows 10.)

I'm not sure if using it from command line fares better, but I can try using that instead.

**Comment by nununoisy** [comment]
I took a look and it actually seems that the code that decides whether or not the input is a GBS or LSDj ROM depends on the file extension being lowercase. That should be an easy fix for the next release, though I would like to refactor it to look for magic bytes instead. As a workaround, you can try renaming the file.

Would you mind sending the GBS to me somehow so I can test the metadata extraction on CJK characters? You can drop it here or DM me on Discord if you want.

**Comment by N-SPC700** [comment]
I uploaded them in that post. See the JPMetadata.zip link. I hope those help.

**Comment by nununoisy** [comment]
Didn't see that, thanks! I'll try to have a fix out for this quickly.

**Comment by nununoisy** [comment]
Quick update on this - I'm now matching/validating files based on magic bytes instead of extensions. However, the JP GBSes still don't work. I think that it's because the titles are encoded as Shift-JIS instead of UTF-8. I'll start working on getting that working properly.

**Comment by nununoisy** [comment]
Fixed in v0.1.1.
