### ISSUE TITLE
Song selection not working on latest LSDJ stable version (9.3.9)

### ISSUE THREAD

**Issue by laamaa** [nununoisy/gb-presenter-rs#3]
(Platform: Linux/Fedora 38)

It seems that the application is unable to select the correct song when using the latest stable version 9.3.9 of LSDJ and plays just whatever is there when LSDJ starts.

Previous 9.2.L works fine.

I checked that the input combos for selecting the song should be the same, no idea what could've changed between the versions...

**Comment by nununoisy** [comment]
Hmm, weird. It could just be that something is a bit laggier in the newest version and the button presses are too fast to take effect. I've been meaning to revamp the joypad macro system anyways but it seems I have a good reason to now.

**Comment by nununoisy** [comment]
Should be fixed in v0.2.0, if it still isn't working you can reopen this issue.
