### ISSUE TITLE
Window needs scrollbar on lower resolutions / smaller screens.

### ISSUE THREAD

**Issue by sttng** [nununoisy/gb-presenter-rs#7]
![Capture](https://github.com/nununoisy/gb-presenter-rs/assets/46765778/19065b5c-729d-49ce-be25-6a8d965319ef)
As shown in the screenshot when using for example LSDJ files, the bottom of the Application is no longer displayed.

**Comment by nununoisy** [comment]
I've made the visualizer config panel collapsible in v0.6.1. That should fix this issue, but if it's still not usable in some situation because of the window height, feel free to re-open this bug.

**Comment by Tachytaenius** [comment]
Still an issue with 2x mode and a height of 1080 pixels. An option to make the whole window contents' scale less huge (it is pretty big) would help.

Thanks for making this awesome program! :3

**Comment by Tachytaenius** [comment]
(pls reopen issue kthxbai)
